#!/bin/sh

xgettext --language=Python --keyword=_ --output=mint-common.pot usr/share/linuxmint/common/mint-which-launcher.py usr/share/linuxmint/common/mint-remove-application.py generate_additional_files.py


