#!/bin/bash

xgettext --language=Python --keyword=_ --output=mint-common.pot usr/bin/* usr/lib/python3/dist-packages/mintcommon/*.py usr/lib/python3/dist-packages/mintcommon/installer/*.py usr/lib/linuxmint/common/*


